### ISSUE TITLE
README doc still leaving me going "huh?"

### ISSUE THREAD

**Issue by bentito** [eliaz/mycodeinterpreter#1]
I feel like you've got something pretty cool here and I really want to understand it, can you maybe add some to the README?. Maybe a preliminary section like "Why you want to do this? (and answer)" and maybe some more practical examples that show why this is better or different than just asking code questions to GPT?

**Comment by eliaz** [comment]
Nice that you find it interesting.  
"add some to the README?"
yeah , the documentation is bad. I added a video now that likely gives an intuition for how it works. I also made the docker thing work better now so its safer to test yourself, however - you should now that the ngrok url is exposed without security for exec calls into the docker.

"why this is better or different than just asking code questions to GPT?"
It gives chatgpt access to YOUR environment , so it can execute any cli command there. The code-interpreter environment chatgpt provides does not have the same privileges as it has on your own server. In the video example you can for example see it installing the  packages it needs  from internet, the chatgpt-code interpreter environment could not do this. 

""Why you want to do this? " This is a good question, and one I dont have any better answer to than "I could not resist". It is likely that using the API  like for example [shellGpt](https://github.com/TheR1D/shell_gpt) is actually a better approach then this. It is likely I will not work on this anymore, but its still fun to play around with.

**Comment by bentito** [comment]
That's awesome! Video worth a million words. TY
